version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
  gcp-gke: circleci/gcp-gke@1.3.0

jobs:
  build-push-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.13         
      - gcp-gcr/build-image:
          docker-context: .
          dockerfile: Dockerfile
          google-project-id: GOOGLE_PROJECT_ID
          image: aman-test
          registry-url: "gcr.io"
          path: . 
          tag: latest
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GCP_PROJECT_KEY
          google-compute-region: GOOGLE_COMPUTE_REGION
          google-compute-zone: GOOGLE_COMPUTE_ZONE
          google-project-id: GOOGLE_PROJECT_ID
      - gcp-gcr/push-image:
          registry-url: gcr.io
          image: aman-test
          google-project-id: GOOGLE_PROJECT_ID
          tag: latest

  deploy-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
         version: 19.03.13
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GCP_PROJECT_KEY
          google-compute-region: GOOGLE_COMPUTE_REGION
          google-compute-zone: GOOGLE_COMPUTE_ZONE
          google-project-id: GOOGLE_PROJECT_ID         
      - gcp-gke/rollout-image:
          cluster: aman-test-circleci
          container: aman-html 
          deployment: httpd 
          dry-run: server 
          image: aman-test
          namespace: default
          tag: latest 


workflows:  
  workflow-build-push-image-aman:    
    jobs:
      - build-push-job:
          context: tech-session-var
      - deploy-job:
          context: tech-session-var
          requires:
            - build-push-job 
  post-steps:
            - run:
                command: kubectl rollout restart deployments/$DEPLOYMENT_NAME
